# Read the Docs configuration file
version: 2

# Set the OS, Python version and install dolfinx and multiphenicsx
build:
   os: ubuntu-22.04
   tools:
      python: "mambaforge-22.9"

conda:
  environment: docs/source/rtd_environment.yml

# Build the docs in additional formats
# formats:
#    - pdf

# Build documentation in the "docs/" directory with Sphinx
sphinx:
   configuration: docs/source/conf.py
