name: rtd_environment
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.10
  - pip
  - fenics-dolfinx
  - mpich
  - pip:
    - git+https://github.com/multiphenics/multiphenicsx.git
    - git+https://github.com/cidetec-energy-storage/cideMOD.git
    - Sphinx==7.2.4
    - sphinx-rtd-theme
    - sphinxcontrib-bibtex